# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AutoPi.ui'
#
# Created: Wed Apr 30 02:25:52 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AutoPi(object):
    def setupUi(self, AutoPi):
        AutoPi.setObjectName(_fromUtf8("AutoPi"))
        AutoPi.resize(1280, 800)
        self.centralwidget = QtGui.QWidget(AutoPi)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1280, 800))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabDash = QtGui.QWidget()
        self.tabDash.setObjectName(_fromUtf8("tabDash"))
        self.line = QtGui.QFrame(self.tabDash)
        self.line.setGeometry(QtCore.QRect(640, 60, 20, 691))
        self.line.setLineWidth(5)
        self.line.setMidLineWidth(5)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.groupBox = QtGui.QGroupBox(self.tabDash)
        self.groupBox.setGeometry(QtCore.QRect(40, 0, 591, 251))
        font = QtGui.QFont()
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lcdNumberRPM = QtGui.QLCDNumber(self.groupBox)
        self.lcdNumberRPM.setGeometry(QtCore.QRect(20, 100, 571, 151))
        self.lcdNumberRPM.setObjectName(_fromUtf8("lcdNumberRPM"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.tabDash)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(670, 450, 591, 151))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_Back = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_Back.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton_Back.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Back.setStyleSheet(_fromUtf8(""))
        self.pushButton_Back.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Media Buttons/Oxygen-Icons.org-Oxygen-Actions-media-skip-backward.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Back.setIcon(icon)
        self.pushButton_Back.setIconSize(QtCore.QSize(128, 128))
        self.pushButton_Back.setObjectName(_fromUtf8("pushButton_Back"))
        self.horizontalLayout_2.addWidget(self.pushButton_Back)
        self.pushButton_Play = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_Play.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton_Play.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Play.setStyleSheet(_fromUtf8(""))
        self.pushButton_Play.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Media Buttons/Oxygen-Icons.org-Oxygen-Actions-media-playback-start.ico")), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Play/Oxygen-Icons.org-Oxygen-Actions-media-playback-start.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_Play.setIcon(icon1)
        self.pushButton_Play.setIconSize(QtCore.QSize(128, 128))
        self.pushButton_Play.setObjectName(_fromUtf8("pushButton_Play"))
        self.horizontalLayout_2.addWidget(self.pushButton_Play)
        self.pushButton_Next = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_Next.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton_Next.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Next.setStyleSheet(_fromUtf8(""))
        self.pushButton_Next.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Media Buttons/Oxygen-Icons.org-Oxygen-Actions-media-skip-forward.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Next.setIcon(icon2)
        self.pushButton_Next.setIconSize(QtCore.QSize(128, 128))
        self.pushButton_Next.setObjectName(_fromUtf8("pushButton_Next"))
        self.horizontalLayout_2.addWidget(self.pushButton_Next)
        self.lineEditNowPlaying = QtGui.QLineEdit(self.tabDash)
        self.lineEditNowPlaying.setGeometry(QtCore.QRect(670, 380, 591, 61))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.lineEditNowPlaying.setFont(font)
        self.lineEditNowPlaying.setObjectName(_fromUtf8("lineEditNowPlaying"))
        self.groupBox_2 = QtGui.QGroupBox(self.tabDash)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 250, 591, 251))
        font = QtGui.QFont()
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.lcdNumberMPH = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumberMPH.setGeometry(QtCore.QRect(20, 100, 571, 151))
        self.lcdNumberMPH.setObjectName(_fromUtf8("lcdNumberMPH"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.tabDash)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(669, 600, 591, 141))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_Rewind = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Rewind.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton_Rewind.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Rewind.setStyleSheet(_fromUtf8(""))
        self.pushButton_Rewind.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Media Buttons/Oxygen-Icons.org-Oxygen-Actions-media-seek-backward.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Play/Oxygen-Icons.org-Oxygen-Actions-media-playback-start.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Media Buttons/Oxygen-Icons.org-Oxygen-Actions-media-playback-start.ico")), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.pushButton_Rewind.setIcon(icon3)
        self.pushButton_Rewind.setIconSize(QtCore.QSize(128, 128))
        self.pushButton_Rewind.setObjectName(_fromUtf8("pushButton_Rewind"))
        self.horizontalLayout.addWidget(self.pushButton_Rewind)
        self.pushButton_Stop = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Stop.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton_Stop.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Stop.setStyleSheet(_fromUtf8(""))
        self.pushButton_Stop.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Media Buttons/Oxygen-Icons.org-Oxygen-Actions-media-playback-stop.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Play/Oxygen-Icons.org-Oxygen-Actions-media-playback-start.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Media Buttons/Oxygen-Icons.org-Oxygen-Actions-media-playback-start.ico")), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.pushButton_Stop.setIcon(icon4)
        self.pushButton_Stop.setIconSize(QtCore.QSize(128, 128))
        self.pushButton_Stop.setObjectName(_fromUtf8("pushButton_Stop"))
        self.horizontalLayout.addWidget(self.pushButton_Stop)
        self.pushButton_FF = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_FF.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton_FF.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_FF.setStyleSheet(_fromUtf8(""))
        self.pushButton_FF.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Media Buttons/Oxygen-Icons.org-Oxygen-Actions-media-seek-forward.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Play/Oxygen-Icons.org-Oxygen-Actions-media-playback-start.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Media Buttons/Oxygen-Icons.org-Oxygen-Actions-media-playback-start.ico")), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.pushButton_FF.setIcon(icon5)
        self.pushButton_FF.setIconSize(QtCore.QSize(128, 128))
        self.pushButton_FF.setObjectName(_fromUtf8("pushButton_FF"))
        self.horizontalLayout.addWidget(self.pushButton_FF)
        self.verticalSliderThrottle = QtGui.QSlider(self.tabDash)
        self.verticalSliderThrottle.setGeometry(QtCore.QRect(10, 279, 29, 191))
        self.verticalSliderThrottle.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderThrottle.setObjectName(_fromUtf8("verticalSliderThrottle"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tabDash)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 470, 61, 31))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.groupBox_3 = QtGui.QGroupBox(self.tabDash)
        self.groupBox_3.setGeometry(QtCore.QRect(660, 0, 591, 251))
        font = QtGui.QFont()
        font.setPointSize(66)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.lcdNumberCoolantTemp = QtGui.QLCDNumber(self.groupBox_3)
        self.lcdNumberCoolantTemp.setGeometry(QtCore.QRect(20, 100, 490, 151))
        self.lcdNumberCoolantTemp.setObjectName(_fromUtf8("lcdNumberCoolantTemp"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(510, 80, 81, 141))
        font = QtGui.QFont()
        font.setPointSize(66)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalSliderLoad = QtGui.QSlider(self.tabDash)
        self.verticalSliderLoad.setGeometry(QtCore.QRect(10, 30, 29, 191))
        self.verticalSliderLoad.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderLoad.setObjectName(_fromUtf8("verticalSliderLoad"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tabDash)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 220, 50, 42))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setEnabled(True)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.tabWidget.addTab(self.tabDash, _fromUtf8(""))
        self.tabDTC = QtGui.QWidget()
        self.tabDTC.setObjectName(_fromUtf8("tabDTC"))
        self.tableWidget = QtGui.QTableWidget(self.tabDTC)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 795, 545))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.tabWidget.addTab(self.tabDTC, _fromUtf8(""))
        AutoPi.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(AutoPi)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        AutoPi.setStatusBar(self.statusbar)

        self.retranslateUi(AutoPi)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AutoPi)

    def retranslateUi(self, AutoPi):
        AutoPi.setWindowTitle(_translate("AutoPi", "AutoPi", None))
        self.groupBox.setTitle(_translate("AutoPi", "RPM", None))
        self.lineEditNowPlaying.setText(_translate("AutoPi", "Song Name", None))
        self.groupBox_2.setTitle(_translate("AutoPi", "MPH", None))
        self.label.setText(_translate("AutoPi", "Throttle", None))
        self.label_2.setText(_translate("AutoPi", "Position", None))
        self.groupBox_3.setTitle(_translate("AutoPi", "Coolant Temp", None))
        self.label_5.setText(_translate("AutoPi", "°C", None))
        self.label_3.setText(_translate("AutoPi", "Engine", None))
        self.label_4.setText(_translate("AutoPi", "Load", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDash), _translate("AutoPi", "Dashboard", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("AutoPi", "Date/Time", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("AutoPi", "Code #", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("AutoPi", "Description", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDTC), _translate("AutoPi", "DTC", None))

import Media_Buttons_rc
