# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AutoPi.ui'
#
# Created: Tue Apr 29 19:40:17 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AutoPi(object):
    def setupUi(self, AutoPi):
        AutoPi.setObjectName(_fromUtf8("AutoPi"))
        AutoPi.resize(1280, 800)
        self.centralwidget = QtGui.QWidget(AutoPi)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1280, 800))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabDash = QtGui.QWidget()
        self.tabDash.setObjectName(_fromUtf8("tabDash"))
        self.line = QtGui.QFrame(self.tabDash)
        self.line.setGeometry(QtCore.QRect(640, 60, 20, 691))
        self.line.setLineWidth(5)
        self.line.setMidLineWidth(5)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.groupBox = QtGui.QGroupBox(self.tabDash)
        self.groupBox.setGeometry(QtCore.QRect(40, 0, 591, 251))
        font = QtGui.QFont()
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lcdNumberRPM = QtGui.QLCDNumber(self.groupBox)
        self.lcdNumberRPM.setGeometry(QtCore.QRect(20, 100, 571, 151))
        self.lcdNumberRPM.setObjectName(_fromUtf8("lcdNumberRPM"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.tabDash)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(680, 590, 571, 151))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_Back = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_Back.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton_Back.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Back.setStyleSheet(_fromUtf8(""))
        self.pushButton_Back.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Media Buttons/Oxygen-Icons.org-Oxygen-Actions-media-skip-backward.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Back.setIcon(icon)
        self.pushButton_Back.setIconSize(QtCore.QSize(128, 128))
        self.pushButton_Back.setObjectName(_fromUtf8("pushButton_Back"))
        self.horizontalLayout_2.addWidget(self.pushButton_Back)
        self.pushButton_Play = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_Play.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton_Play.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Play.setStyleSheet(_fromUtf8(""))
        self.pushButton_Play.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Media Buttons/Oxygen-Icons.org-Oxygen-Actions-media-playback-start.ico")), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Play/Oxygen-Icons.org-Oxygen-Actions-media-playback-start.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_Play.setIcon(icon1)
        self.pushButton_Play.setIconSize(QtCore.QSize(128, 128))
        self.pushButton_Play.setObjectName(_fromUtf8("pushButton_Play"))
        self.horizontalLayout_2.addWidget(self.pushButton_Play)
        self.pushButton_Next = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_Next.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton_Next.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Next.setStyleSheet(_fromUtf8(""))
        self.pushButton_Next.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Media Buttons/Oxygen-Icons.org-Oxygen-Actions-media-skip-forward.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Next.setIcon(icon2)
        self.pushButton_Next.setIconSize(QtCore.QSize(128, 128))
        self.pushButton_Next.setObjectName(_fromUtf8("pushButton_Next"))
        self.horizontalLayout_2.addWidget(self.pushButton_Next)
        self.lineEdit = QtGui.QLineEdit(self.tabDash)
        self.lineEdit.setGeometry(QtCore.QRect(680, 520, 571, 61))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.groupBox_2 = QtGui.QGroupBox(self.tabDash)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 250, 591, 251))
        font = QtGui.QFont()
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.lcdNumberRPM_3 = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumberRPM_3.setGeometry(QtCore.QRect(20, 100, 571, 151))
        self.lcdNumberRPM_3.setObjectName(_fromUtf8("lcdNumberRPM_3"))
        self.tabWidget.addTab(self.tabDash, _fromUtf8(""))
        self.tabDTC = QtGui.QWidget()
        self.tabDTC.setObjectName(_fromUtf8("tabDTC"))
        self.tableWidget = QtGui.QTableWidget(self.tabDTC)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 795, 545))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.tabWidget.addTab(self.tabDTC, _fromUtf8(""))
        AutoPi.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(AutoPi)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        AutoPi.setStatusBar(self.statusbar)

        self.retranslateUi(AutoPi)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AutoPi)

    def retranslateUi(self, AutoPi):
        AutoPi.setWindowTitle(_translate("AutoPi", "AutoPi", None))
        self.groupBox.setTitle(_translate("AutoPi", "RPM", None))
        self.lineEdit.setText(_translate("AutoPi", "Song Name", None))
        self.groupBox_2.setTitle(_translate("AutoPi", "MPH", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDash), _translate("AutoPi", "Dashboard", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("AutoPi", "Date/Time", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("AutoPi", "Code #", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("AutoPi", "Description", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDTC), _translate("AutoPi", "DTC", None))

import Media_Buttons_rc
